// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BddTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RegrasDeDescontoPorQuantidadeFeature : object, Xunit.IClassFixture<RegrasDeDescontoPorQuantidadeFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RegrasDeDesconto.feature"
#line hidden
        
        public RegrasDeDescontoPorQuantidadeFeature(RegrasDeDescontoPorQuantidadeFeature.FixtureData fixtureData, BddTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Regras de Desconto por Quantidade", "  Como sistema de vendas\r\n  Eu preciso aplicar descontos automáticos baseados na " +
                    "quantidade\r\n  Para incentivar compras maiores", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Aplicar desconto baseado na quantidade")]
        [Xunit.TraitAttribute("FeatureTitle", "Regras de Desconto por Quantidade")]
        [Xunit.TraitAttribute("Description", "Aplicar desconto baseado na quantidade")]
        [Xunit.InlineDataAttribute("1", "0", "100.00", new string[0])]
        [Xunit.InlineDataAttribute("2", "0", "200.00", new string[0])]
        [Xunit.InlineDataAttribute("3", "0", "300.00", new string[0])]
        [Xunit.InlineDataAttribute("4", "0", "400.00", new string[0])]
        [Xunit.InlineDataAttribute("5", "10", "450.00", new string[0])]
        [Xunit.InlineDataAttribute("9", "10", "810.00", new string[0])]
        [Xunit.InlineDataAttribute("10", "20", "800.00", new string[0])]
        [Xunit.InlineDataAttribute("15", "20", "1200.00", new string[0])]
        [Xunit.InlineDataAttribute("20", "20", "1600.00", new string[0])]
        public void AplicarDescontoBaseadoNaQuantidade(string quantidade, string desconto, string valor_Total, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("quantidade", quantidade);
            argumentsOfScenario.Add("desconto", desconto);
            argumentsOfScenario.Add("valor_total", valor_Total);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Aplicar desconto baseado na quantidade", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
    testRunner.Given("que estou criando uma venda", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    testRunner.When(string.Format("eu adicionar {0} itens com valor unitário de R$ 100,00", quantidade), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
    testRunner.Then(string.Format("o desconto aplicado deve ser {0}%", desconto), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 10
    testRunner.And(string.Format("o valor total do item deve ser R$ {0}", valor_Total), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não permitir venda acima de 20 itens")]
        [Xunit.TraitAttribute("FeatureTitle", "Regras de Desconto por Quantidade")]
        [Xunit.TraitAttribute("Description", "Não permitir venda acima de 20 itens")]
        public void NaoPermitirVendaAcimaDe20Itens()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não permitir venda acima de 20 itens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 25
    testRunner.Given("que estou criando uma venda", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 26
    testRunner.When("eu tentar adicionar 21 itens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
    testRunner.Then("a venda não deve ser criada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
    testRunner.And("deve retornar erro de validação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
    testRunner.And("a mensagem deve indicar que quantidade > 20 é proibida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não permitir desconto para menos de 4 itens")]
        [Xunit.TraitAttribute("FeatureTitle", "Regras de Desconto por Quantidade")]
        [Xunit.TraitAttribute("Description", "Não permitir desconto para menos de 4 itens")]
        public void NaoPermitirDescontoParaMenosDe4Itens()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não permitir desconto para menos de 4 itens", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 32
    testRunner.Given("que estou criando uma venda", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
    testRunner.When("eu adicionar 3 itens", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("não deve aplicar nenhum desconto", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
    testRunner.And("o valor total deve ser o valor bruto", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RegrasDeDescontoPorQuantidadeFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RegrasDeDescontoPorQuantidadeFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
